name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app

    # No global installation
    # -- npx create-react-app --template typescript react-app
    # -- cd react-app && npm run start
    # -- recreate lock run npm install

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # 1. Install deps of our react application
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: npm ci
      # 2. Execute automated tests for our react application
      - name: Run unit tests
        run: npm run test
